sync_interval_minutes: 15
log_level: INFO

users:
  - name: "elias"
    eufy:
      email: "elias@example.com"
      password: "${EUFY_PASSWORD_ELIAS}"
    garmin:
      email: "elias@example.com"
      password: "${GARMIN_PASSWORD_ELIAS}"

  # - name: "roommate"
  #   eufy:
  #     email: "roommate@example.com"
  #     password: "${EUFY_PASSWORD_ROOMMATE}"
  #   garmin:
  #     email: "roommate@example.com"
  #     password: "${GARMIN_PASSWORD_ROOMMATE}"
